package service

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	"backend/internal/config"
)

// GeneratorService handles SKILL.md and MCP server script generation.
type GeneratorService struct{}

// NewGeneratorService creates a new GeneratorService.
func NewGeneratorService() *GeneratorService { return &GeneratorService{} }

// ToSlug converts a team name to a Python/filesystem-safe lowercase identifier.
// "Platform Engineering" → "platform_engineering"
func ToSlug(name string) string {
	var sb strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			sb.WriteRune(r)
		case r == ' ', r == '-':
			sb.WriteRune('_')
		}
	}
	s := strings.Trim(sb.String(), "_")
	if s == "" {
		return "team"
	}
	return s
}

// ─── SKILL.md ─────────────────────────────────────────────────────────────────

var skillTemplate = template.Must(template.New("skill").Parse(`# SKILL: {{ .TeamName }} Knowledge Base

> Auto-generated by ` + "`devask skill generate`" + ` on {{ .GeneratedAt }}
> Team ID: ` + "`{{ .TeamID }}`" + `

## About This Team

| Field | Value |
|---|---|
| **Name** | {{ .TeamName }} |
| **Description** | {{ .Description }} |
| **Tech Stack** | {{ .TechStack }} |

## Knowledge Base Coverage

This knowledge base contains {{ .DocCount }} ingested document(s):

{{ range .Documents }}- ` + "`{{ . }}`" + `
{{ else }}- *(no documents ingested yet — run `+"`devask upload <file>`"+`)*
{{ end }}
## How to Query

### CLI
` + "```bash" + `
devask ask "{{ .ExampleQuestion }}"
devask docs
` + "```" + `

### REST API
` + "```bash" + `
curl -X POST http://localhost:8081/ask \
  -H "Content-Type: application/json" \
  -d '{"team_id":"{{ .TeamID }}","question":"{{ .ExampleQuestion }}"}'
` + "```" + `

### MCP Tools (via Claude Desktop)
After running ` + "`devask mcp generate`" + `, Claude can use:
- ` + "`ask_{{ .TeamSlug }}(question)`" + ` — Ask any question to the knowledge base
- ` + "`list_{{ .TeamSlug }}_docs()`" + ` — List all ingested documents

## Notes
- Answers are synthesized by **gpt-oss:120b** (via Ollama) using hybrid retrieval (Pinecone + BM25 + RRF).
- Upload new documents with ` + "`devask upload <file>`" + ` to keep the knowledge base current.
`))

type skillData struct {
	TeamName        string
	TeamID          string
	Description     string
	TechStack       string
	TeamSlug        string
	GeneratedAt     string
	Documents       []string
	DocCount        int
	ExampleQuestion string
}

// GenerateSkill writes a SKILL.md file for the team's knowledge base.
func (g *GeneratorService) GenerateSkill(profile *config.TeamProfile, docs []string, outputPath string) error {
	data := skillData{
		TeamName:    profile.TeamName,
		TeamID:      profile.TeamID,
		Description: profile.Description,
		TechStack:   strings.Join(profile.TechStack, ", "),
		TeamSlug:    ToSlug(profile.TeamName),
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05"),
		Documents:   docs,
		DocCount:    len(docs),
		ExampleQuestion: fmt.Sprintf("How does %s handle deployments?",
			strings.Split(profile.TeamName, " ")[0]),
	}

	var buf bytes.Buffer
	if err := skillTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("render SKILL.md template: %w", err)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write SKILL.md: %w", err)
	}
	return nil
}

// ─── MCP Server Script ────────────────────────────────────────────────────────

var mcpTemplate = template.Must(template.New("mcp").Parse(`#!/usr/bin/env python3
"""
Devask MCP Server — {{ .TeamName }}
Team ID   : {{ .TeamID }}
Generated : {{ .GeneratedAt }}

Setup:
  pip install mcp httpx
  python {{ .OutputFile }}

Claude Desktop config (~/.config/claude/claude_desktop_config.json):
  {
    "mcpServers": {
      "devask-{{ .TeamSlug }}": {
        "command": "python",
        "args": ["{{ .OutputFile }}"]
      }
    }
  }
"""

import httpx
from mcp.server.fastmcp import FastMCP

# ── Config ────────────────────────────────────────────────────────────────────
DEVASK_SERVER_URL = "{{ .ServerURL }}"
TEAM_ID           = "{{ .TeamID }}"
TEAM_NAME         = "{{ .TeamName }}"
TECH_STACK        = "{{ .TechStack }}"

mcp = FastMCP("devask-{{ .TeamSlug }}")


# ── Tool: ask a question ──────────────────────────────────────────────────────
@mcp.tool()
def ask_{{ .TeamSlug }}(question: str) -> str:
    """
    Ask a question to the {{ .TeamName }} team's private knowledge base.
    Returns a cited answer synthesized by an LLM from the team's ingested documents.
    Tech stack: {{ .TechStack }}
    Use this when you need information about {{ .TeamName }}'s systems, processes, or domain.
    """
    try:
        resp = httpx.post(
            f"{DEVASK_SERVER_URL}/ask",
            json={"team_id": TEAM_ID, "question": question},
            timeout=90.0,
        )
        resp.raise_for_status()
        data    = resp.json()
        answer  = data.get("answer", "No answer returned.")
        sources = data.get("sources", [])
        mode    = data.get("retrieval_mode", "unknown")
        result  = answer
        if sources:
            result += "\n\n📎 Sources: " + ", ".join(sources)
        result += f"\n🔀 Retrieval: {mode}"
        return result
    except httpx.HTTPStatusError as e:
        return f"Error: HTTP {e.response.status_code} from Devask server."
    except Exception as e:
        return f"Error querying knowledge base: {e}"


# ── Tool: list ingested documents ─────────────────────────────────────────────
@mcp.tool()
def list_{{ .TeamSlug }}_docs() -> str:
    """
    List all documents currently ingested in the {{ .TeamName }} knowledge base.
    """
    try:
        resp = httpx.get(
            f"{DEVASK_SERVER_URL}/docs",
            params={"team_id": TEAM_ID},
            timeout=30.0,
        )
        resp.raise_for_status()
        data = resp.json()
        docs = data.get("documents", [])
        if not docs:
            return "No documents ingested yet. Run: devask upload <file>"
        lines = [f"📚 {TEAM_NAME} knowledge base ({len(docs)} document(s)):", ""]
        lines += [f"  • {d}" for d in docs]
        return "\n".join(lines)
    except Exception as e:
        return f"Error listing documents: {e}"


if __name__ == "__main__":
    mcp.run()
`))

type mcpData struct {
	TeamName    string
	TeamID      string
	TechStack   string
	TeamSlug    string
	GeneratedAt string
	ServerURL   string
	OutputFile  string
}

// GenerateMCP writes a Python MCP server script for the team.
func (g *GeneratorService) GenerateMCP(profile *config.TeamProfile, serverURL, outputFile string) error {
	data := mcpData{
		TeamName:    profile.TeamName,
		TeamID:      profile.TeamID,
		TechStack:   strings.Join(profile.TechStack, ", "),
		TeamSlug:    ToSlug(profile.TeamName),
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05"),
		ServerURL:   serverURL,
		OutputFile:  outputFile,
	}

	var buf bytes.Buffer
	if err := mcpTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("render MCP template: %w", err)
	}

	if err := os.WriteFile(outputFile, buf.Bytes(), 0755); err != nil {
		return fmt.Errorf("write MCP script: %w", err)
	}
	return nil
}
