package service

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	"backend/internal/config"
	"backend/pkg/aiclient"
)

// GeneratorService handles SKILL.md and MCP server script generation.
type GeneratorService struct {
	aiClient  *aiclient.Client // optional — enables AI-powered SKILL.md generation
	serverURL string           // when set, LLM calls are proxied via /llm/complete on this URL
}

// NewGeneratorService creates a new GeneratorService without an AI client.
// The generated SKILL.md will use the static template.
func NewGeneratorService() *GeneratorService { return &GeneratorService{} }

// NewGeneratorServiceWithAI creates a new GeneratorService backed by an AI client
// that calls the LLM API directly.
func NewGeneratorServiceWithAI(ai *aiclient.Client) *GeneratorService {
	return &GeneratorService{aiClient: ai}
}

// NewGeneratorServiceViaServer creates a GeneratorService that routes all LLM
// calls through the Devask server's /llm/complete proxy endpoint.
//
//	serverURL — e.g. "http://localhost:8081" (DEVASK_SERVER_URL)
func NewGeneratorServiceViaServer(ai *aiclient.Client, serverURL string) *GeneratorService {
	return &GeneratorService{aiClient: ai, serverURL: strings.TrimRight(serverURL, "/")}
}

// ToSlug converts a team name to a Python/filesystem-safe lowercase identifier.
// "Platform Engineering" → "platform_engineering"
func ToSlug(name string) string {
	var sb strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			sb.WriteRune(r)
		case r == ' ', r == '-':
			sb.WriteRune('_')
		}
	}
	s := strings.Trim(sb.String(), "_")
	if s == "" {
		return "team"
	}
	return s
}

// ─── SkillOptions ──────────────────────────────────────────────────────────────

// SkillOptions carries optional generation parameters for GenerateSkill.
type SkillOptions struct {
	// ContextChunks are real text excerpts retrieved from the knowledge base.
	// When non-empty these are injected into the prompt so gpt-oss generates
	// the SKILL.md from actual KB content rather than just the team profile.
	ContextChunks []string

	// SkillFocus narrows generation to a single sub-domain from the KB.
	// E.g. "database", "api", "auth", "deployment".
	// When empty a comprehensive SKILL.md covering the full KB is generated.
	SkillFocus string
}

// ─── Static fallback SKILL.md template ───────────────────────────────────────
// Used when the AI client is unavailable or the LLM call fails.

var skillTemplate = template.Must(template.New("skill").Parse(`# SKILL: {{ .TeamName }} Knowledge Base{{ if .SkillFocus }} — {{ .SkillFocus }}{{ end }}

> Auto-generated by ` + "`devask skill generate`" + ` on {{ .GeneratedAt }}
> Team ID: ` + "`{{ .TeamID }}`" + `{{ if .SkillFocus }}
> Skill Focus: **{{ .SkillFocus }}**{{ end }}

## About This Team

| Field | Value |
|---|---|
| **Name** | {{ .TeamName }} |
| **Description** | {{ .Description }} |
| **Tech Stack** | {{ .TechStack }} |

## Knowledge Base Coverage

This knowledge base contains {{ .DocCount }} ingested document(s):

{{ range .Documents }}- ` + "`{{ . }}`" + `
{{ else }}- *(no documents ingested yet — run ` + "`devask upload <file>`" + `)*
{{ end }}
## How to Query

### CLI
` + "```bash" + `
devask ask "{{ .ExampleQuestion }}"
devask docs
` + "```" + `

### REST API
` + "```bash" + `
curl -X POST http://localhost:8081/ask \
  -H "Content-Type: application/json" \
  -d '{"team_id":"{{ .TeamID }}","question":"{{ .ExampleQuestion }}"}'
` + "```" + `

### MCP Tools (via Claude Desktop)
After running ` + "`devask mcp generate`" + `, Claude can use:
- ` + "`ask_{{ .TeamSlug }}(question)`" + ` — Ask any question to the knowledge base
- ` + "`list_{{ .TeamSlug }}_docs()`" + ` — List all ingested documents

## Notes
- Answers are synthesized by **gpt-oss:120b** (via Ollama) using hybrid retrieval (Pinecone + BM25 + RRF).
- Upload new documents with ` + "`devask upload <file>`" + ` to keep the knowledge base current.
`))

type skillData struct {
	TeamName        string
	TeamID          string
	Description     string
	TechStack       string
	TeamSlug        string
	SkillFocus      string
	GeneratedAt     string
	Documents       []string
	DocCount        int
	ExampleQuestion string
}

// ─── AI-powered SKILL.md generation ──────────────────────────────────────────

// buildSkillPrompt constructs the system + user messages sent to gpt-oss.
//
// The system prompt enforces the exact Antigravity / Claude / Cursor SKILL.md
// structure. The user message injects:
//   - Team profile metadata (name, ID, description, tech stack)
//   - Real text chunks retrieved from the knowledge base (Pinecone + BM25)
//   - An optional SkillFocus to narrow the output to a single sub-domain
func buildSkillPrompt(
	profile *config.TeamProfile,
	docs []string,
	opts SkillOptions,
	teamID, teamSlug, generatedAt string,
) []aiclient.Message {

	// ── Format document list ───────────────────────────────────────────────────
	docList := "(no documents ingested yet)"
	if len(docs) > 0 {
		lines := make([]string, len(docs))
		for i, d := range docs {
			lines[i] = "  - " + d
		}
		docList = strings.Join(lines, "\n")
	}

	// ── Format context chunks ─────────────────────────────────────────────────
	var chunksBlock string
	if len(opts.ContextChunks) > 0 {
		var sb strings.Builder
		sb.WriteString("KNOWLEDGE BASE CONTENT (retrieved text excerpts):\n")
		sb.WriteString("─────────────────────────────────────────────────\n")
		for i, chunk := range opts.ContextChunks {
			sb.WriteString(fmt.Sprintf("[Excerpt %d]\n%s\n\n", i+1, strings.TrimSpace(chunk)))
		}
		sb.WriteString("─────────────────────────────────────────────────\n")
		chunksBlock = sb.String()
	} else {
		chunksBlock = "(No context chunks retrieved — generate from team profile metadata only.)\n"
	}

	// ── Skill focus directive ─────────────────────────────────────────────────
	focusDirective := ""
	if opts.SkillFocus != "" {
		focusDirective = fmt.Sprintf(`
IMPORTANT — SKILL FOCUS: "%s"
Generate a SKILL.md that is EXCLUSIVELY focused on the "%s" sub-domain.
- Only extract knowledge relevant to "%s" from the excerpts above.
- Capabilities, Example Queries, Limitations, and the Overview must ALL be scoped to "%s".
- The H1 title must read:  # SKILL: %s — %s
- Ignore content in the excerpts that is unrelated to "%s".
`,
			opts.SkillFocus,
			opts.SkillFocus, opts.SkillFocus, opts.SkillFocus,
			profile.TeamName, opts.SkillFocus,
			opts.SkillFocus,
		)
	}

	techStack := strings.Join(profile.TechStack, ", ")
	domain := inferDomain(profile.TechStack, profile.Description)

	// ── System prompt: AI coding skill/guide schema ───────────────────────────
	system := `You are an expert technical writer that specialises in writing SKILL.md files for AI coding assistants (Antigravity, Claude, Cursor, Copilot).

A SKILL.md in this context is NOT a knowledge-base query guide. It is an AI DEVELOPER SKILL FILE — equivalent to a .cursorrules file, CLAUDE.md, or an Antigravity skill instruction set.

Its purpose is to tell an AI coding assistant:
1. How this part of the system is architected and WHY those decisions were made
2. The exact coding conventions, patterns, and rules to follow when extending it
3. The file/directory structure and where new code belongs
4. Concrete code patterns (with real examples from the codebase) to replicate
5. Explicit DO / DON'T rules the AI must obey when writing code for this domain
6. How this domain integrates with the rest of the system

Use the REAL KB excerpts provided as primary evidence — extract actual code patterns, struct names, function names, file paths, and conventions from them. Do NOT invent patterns not supported by the excerpts.

MANDATORY STRUCTURE (follow EXACTLY — do not rename, reorder, or skip sections):

# SKILL: <TeamName> — <domain or SkillFocus> Development Guide

> <one-sentence purpose: what this skill file teaches an AI assistant to do>

---

## Purpose

This skill file guides AI coding assistants when developing or extending the **<domain/focus>** layer of the <TeamName> codebase. Read this before writing any code related to <domain>.

---

## Architecture Overview

<3–5 sentence description of how this domain/layer is structured. Reference actual components, file paths, struct names, or functions found in the KB excerpts. Explain the key architectural decisions and constraints.>

**Key components:**
| Component | Role | Location |
|---|---|---|
| <component name from excerpts> | <what it does> | <file path or package> |
| <component 2> | <role> | <location> |
| <component 3> | <role> | <location> |
(at least 3 components from the actual KB excerpts)

---

## Coding Conventions

Rules that MUST be followed when writing code in this domain:

### Naming
- <naming rule 1 extracted from excerpts — e.g. function naming, struct naming>
- <naming rule 2>

### Structure
- <structural rule 1 — e.g. package layout, file organisation>
- <structural rule 2>

### Patterns
- <pattern 1 — e.g. error handling, logging, middleware>
- <pattern 2>

---

## File & Package Structure

` + "```" + `
<reproduce the relevant directory tree from the KB excerpts, annotated>
<e.g.:>
backend/
  internal/
    service/      # business logic — one file per domain service
    cli/          # cobra commands — one file per command group
  pkg/
    aiclient/     # OpenAI-compatible LLM client
    pyclient/     # Python AI microservice HTTP client
` + "```" + `

---

## Implementation Patterns

Show the canonical way to implement common tasks in this domain. Extract ACTUAL code snippets or patterns from the KB excerpts where possible.

### Pattern 1: <name of pattern from excerpts>
<when to use this pattern>
` + "```go" + `
// <actual or representative code from the KB excerpts>
` + "```" + `

### Pattern 2: <name of pattern>
<when to use this pattern>
` + "```go" + `
// <code>
` + "```" + `

### Pattern 3: <name of pattern>
<when to use this pattern>
` + "```go" + `
// <code>
` + "```" + `

(include at least 3 patterns — more if the excerpts support them)

---

## Integration Points

How this domain connects to the rest of the system:

| Integrates with | Via | Purpose |
|---|---|---|
| <other component/service> | <HTTP / function call / shared struct / etc.> | <why> |
| <other component> | <mechanism> | <why> |

**Data flow:**
` + "```" + `
<ASCII diagram or numbered steps showing how data flows through this domain>
e.g.:
CLI command → service layer → pyclient → Python AI microservice → Pinecone
` + "```" + `

---

## DO / DON'T Rules

### ✅ DO
- <concrete rule 1 — specific to this domain, not generic advice>
- <concrete rule 2>
- <concrete rule 3>
- <concrete rule 4>
- <concrete rule 5>

### ❌ DON'T
- <antipattern 1 — specific to this codebase, with reason>
- <antipattern 2>
- <antipattern 3>
- <antipattern 4>
- <antipattern 5>

---

## Extension Guide

When adding a new feature to this domain, follow these steps:

1. **<Step 1>** — <concrete instruction>
2. **<Step 2>** — <concrete instruction>
3. **<Step 3>** — <concrete instruction>
4. **<Step 4>** — <concrete instruction>
5. **<Step 5>** — build and test: ` + "`go build ./... && go test ./...`" + `

---

## Metadata

| Field | Value |
|---|---|
| **Team** | TEAM_NAME_PLACEHOLDER |
| **Team ID** | ` + "`TEAM_ID_PLACEHOLDER`" + ` |
| **Domain / Focus** | SKILL_FOCUS_PLACEHOLDER |
| **Generated** | GENERATED_AT_PLACEHOLDER |
| **Context Chunks** | CHUNK_COUNT_PLACEHOLDER KB excerpts analysed |
| **Model** | gpt-oss:120b (via Ollama) |
| **Documents** | DOC_COUNT_PLACEHOLDER ingested |

> 💡 Keep this file up to date as the codebase evolves.
> Regenerate with ` + "`devask skill generate --skill <focus>`" + ` after uploading new architecture docs.`

	// ── Focus label for metadata ───────────────────────────────────────────────
	focusLabel := "Full knowledge base"
	if opts.SkillFocus != "" {
		focusLabel = opts.SkillFocus
	}

	// ── User message: inject all real data ────────────────────────────────────
	user := fmt.Sprintf(`Generate a SKILL.md for the following team.
Follow the EXACT structure from the system prompt.
Replace ALL placeholder tokens (TEAM_NAME_PLACEHOLDER etc.) with the actual values listed below.
Do NOT include angle brackets <> in the output — replace every placeholder with real content.
%s
━━━ TEAM PROFILE ━━━
Team Name     : %s
Team ID       : %s
Team Slug     : %s
Description   : %s
Tech Stack    : %s
Domain        : %s
Generated At  : %s
Skill Focus   : %s
Doc Count     : %d
Chunk Count   : %d

Ingested Documents:
%s

━━━ KNOWLEDGE BASE EXCERPTS ━━━
%s
Use the excerpts above as the primary source of truth. The more specific and grounded in the excerpts your output is, the better.`,
		focusDirective,
		profile.TeamName, teamID, teamSlug,
		profile.Description, techStack, domain, generatedAt,
		focusLabel, len(docs), len(opts.ContextChunks),
		docList, chunksBlock,
	)

	return []aiclient.Message{
		{Role: "system", Content: system},
		{Role: "user", Content: user},
	}
}

// inferDomain maps tech stack keywords to a human-readable domain label.
func inferDomain(stack []string, desc string) string {
	combined := strings.ToLower(strings.Join(stack, " ") + " " + desc)
	switch {
	case containsAny(combined, "kubernetes", "k8s", "helm", "terraform", "ansible", "docker", "ci/cd", "devops", "infra"):
		return "DevOps / Platform Engineering"
	case containsAny(combined, "react", "vue", "angular", "nextjs", "svelte", "tailwind", "frontend", "ui", "ux"):
		if containsAny(combined, "go", "python", "java", "node", "django", "fastapi", "gin", "express") {
			return "Full-Stack Engineering"
		}
		return "Frontend Engineering"
	case containsAny(combined, "spark", "kafka", "airflow", "databricks", "dbt", "redshift", "bigquery", "snowflake", "etl", "pipeline", "data"):
		return "Data Platform / Analytics Engineering"
	case containsAny(combined, "ml", "llm", "pytorch", "tensorflow", "scikit", "embedding", "model", "inference", "ai"):
		return "AI / ML Engineering"
	case containsAny(combined, "go", "python", "java", "node", "rust", "grpc", "rest", "api", "backend", "microservice", "sql", "postgres", "mysql", "mongo"):
		return "Backend Engineering"
	default:
		return "Software Engineering"
	}
}

func containsAny(s string, keywords ...string) bool {
	for _, kw := range keywords {
		if strings.Contains(s, kw) {
			return true
		}
	}
	return false
}

// ─── GenerateSkill (public entry point) ──────────────────────────────────────

// GenerateSkill writes a SKILL.md file for the team's knowledge base.
//
// opts.ContextChunks — real text excerpts from the KB, retrieved by the CLI
// opts.SkillFocus    — optional sub-domain focus (e.g. "database", "api")
//
// If an AI client is configured, gpt-oss generates the file grounded in the
// actual KB chunks.  If the AI client is nil or the LLM call fails, the static
// template is used as a fallback so the command always succeeds.
func (g *GeneratorService) GenerateSkill(
	profile *config.TeamProfile,
	docs []string,
	opts SkillOptions,
	outputPath string,
) error {
	generatedAt := time.Now().Format("2006-01-02 15:04:05")
	teamSlug := ToSlug(profile.TeamName)

	// ── AI path ───────────────────────────────────────────────────────────────
	if g.aiClient != nil {
		focusMsg := ""
		if opts.SkillFocus != "" {
			focusMsg = fmt.Sprintf(" (focus: %s)", opts.SkillFocus)
		}

		via := "direct"
		if g.serverURL != "" {
			via = g.serverURL + "/llm/complete"
		}
		fmt.Printf("  🤖 Calling %s to generate SKILL.md%s (%d KB chunks) via %s...\n",
			g.aiClient.Model(), focusMsg, len(opts.ContextChunks), via)

		messages := buildSkillPrompt(profile, docs, opts, profile.TeamID, teamSlug, generatedAt)

		var (content string; err error)
		if g.serverURL != "" {
			content, err = g.aiClient.CompleteViaServer(g.serverURL, messages)
		} else {
			content, err = g.aiClient.Complete(messages)
		}

		if err != nil {
			fmt.Printf("  ⚠ AI generation failed (%v). Falling back to static template.\n", err)
		} else {
			content = strings.TrimSpace(content) + "\n"
			if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
				return fmt.Errorf("write SKILL.md: %w", err)
			}
			return nil
		}
	}

	// ── Static fallback ───────────────────────────────────────────────────────
	firstWord := strings.Split(profile.TeamName, " ")[0]
	exampleQ := fmt.Sprintf("How does %s handle deployments?", firstWord)
	if opts.SkillFocus != "" {
		exampleQ = fmt.Sprintf("How does %s manage the %s layer?", firstWord, opts.SkillFocus)
	}

	data := skillData{
		TeamName:        profile.TeamName,
		TeamID:          profile.TeamID,
		Description:     profile.Description,
		TechStack:       strings.Join(profile.TechStack, ", "),
		TeamSlug:        teamSlug,
		SkillFocus:      opts.SkillFocus,
		GeneratedAt:     generatedAt,
		Documents:       docs,
		DocCount:        len(docs),
		ExampleQuestion: exampleQ,
	}

	var buf bytes.Buffer
	if err := skillTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("render SKILL.md template: %w", err)
	}
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write SKILL.md: %w", err)
	}
	return nil
}

// ─── MCP Server Script ────────────────────────────────────────────────────────

var mcpTemplate = template.Must(template.New("mcp").Parse(`#!/usr/bin/env python3
"""
Devask MCP Server — {{ .TeamName }}
Team ID   : {{ .TeamID }}
Generated : {{ .GeneratedAt }}

Setup:
  pip install mcp httpx
  python {{ .OutputFile }}

Claude Desktop config (~/.config/claude/claude_desktop_config.json):
  {
    "mcpServers": {
      "devask-{{ .TeamSlug }}": {
        "command": "python",
        "args": ["{{ .OutputFile }}"]
      }
    }
  }
"""

import httpx
from mcp.server.fastmcp import FastMCP

# ── Config ────────────────────────────────────────────────────────────────────
DEVASK_SERVER_URL = "{{ .ServerURL }}"
TEAM_ID           = "{{ .TeamID }}"
TEAM_NAME         = "{{ .TeamName }}"
TECH_STACK        = "{{ .TechStack }}"

mcp = FastMCP("devask-{{ .TeamSlug }}")


# ── Tool: ask a question ──────────────────────────────────────────────────────
@mcp.tool()
def ask_{{ .TeamSlug }}(question: str) -> str:
    """
    Ask a question to the {{ .TeamName }} team's private knowledge base.
    Returns a cited answer synthesized by an LLM from the team's ingested documents.
    Tech stack: {{ .TechStack }}
    Use this when you need information about {{ .TeamName }}'s systems, processes, or domain.
    """
    try:
        resp = httpx.post(
            f"{DEVASK_SERVER_URL}/ask",
            json={"team_id": TEAM_ID, "question": question},
            timeout=90.0,
        )
        resp.raise_for_status()
        data    = resp.json()
        answer  = data.get("answer", "No answer returned.")
        sources = data.get("sources", [])
        mode    = data.get("retrieval_mode", "unknown")
        result  = answer
        if sources:
            result += "\n\n📎 Sources: " + ", ".join(sources)
        result += f"\n🔀 Retrieval: {mode}"
        return result
    except httpx.HTTPStatusError as e:
        return f"Error: HTTP {e.response.status_code} from Devask server."
    except Exception as e:
        return f"Error querying knowledge base: {e}"


# ── Tool: list ingested documents ─────────────────────────────────────────────
@mcp.tool()
def list_{{ .TeamSlug }}_docs() -> str:
    """
    List all documents currently ingested in the {{ .TeamName }} knowledge base.
    """
    try:
        resp = httpx.get(
            f"{DEVASK_SERVER_URL}/docs",
            params={"team_id": TEAM_ID},
            timeout=30.0,
        )
        resp.raise_for_status()
        data = resp.json()
        docs = data.get("documents", [])
        if not docs:
            return "No documents ingested yet. Run: devask upload <file>"
        lines = [f"📚 {TEAM_NAME} knowledge base ({len(docs)} document(s)):", ""]
        lines += [f"  • {d}" for d in docs]
        return "\n".join(lines)
    except Exception as e:
        return f"Error listing documents: {e}"


if __name__ == "__main__":
    mcp.run()
`))

type mcpData struct {
	TeamName    string
	TeamID      string
	TechStack   string
	TeamSlug    string
	GeneratedAt string
	ServerURL   string
	OutputFile  string
}

// GenerateMCP writes a Python MCP server script for the team.
func (g *GeneratorService) GenerateMCP(profile *config.TeamProfile, serverURL, outputFile string) error {
	data := mcpData{
		TeamName:    profile.TeamName,
		TeamID:      profile.TeamID,
		TechStack:   strings.Join(profile.TechStack, ", "),
		TeamSlug:    ToSlug(profile.TeamName),
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05"),
		ServerURL:   serverURL,
		OutputFile:  outputFile,
	}

	var buf bytes.Buffer
	if err := mcpTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("render MCP template: %w", err)
	}
	if err := os.WriteFile(outputFile, buf.Bytes(), 0755); err != nil {
		return fmt.Errorf("write MCP script: %w", err)
	}
	return nil
}
